// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package jsons

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (TestStruct) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*TestStruct) UnmarshalJSON([]byte) error        { return nil }
func (TestStruct) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*TestStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TestStruct *TestStruct
